### ISSUE TITLE
Add title to interactive content [mostly html changes, perhaps some js]

### ISSUE THREAD

**Issue by yochannah** [intermine/similarity#10]
## Issue description

In this graph: https://github.com/intermine/similarity/blob/master/Visualisations/top_edges.html, 
when a node is double clicked, a table shows up showing details of the node. Similarly, when it's double clicked, the node and all of its networked nodes shows up. 

It would be nice to add a title to each of these sections if they're visible. How about the following changes

- [ ] `Selected Node: ` above the on-click info
- [ ] `Selected Node + Similar items` for the table heading
- [ ] This text is already present: `Double click on a node to load the table.` let's re-word this to `Double click on a node to load more info about the node and its closest neighbours.`

Also, don't forgot to make sure the headings only show up with it makes sense for them to be present, e.g. when their content is displayed. 

## If you'd like to pick this up:

1. Leave a comment to say you're working on the issue
2. Fork the repo, implement the code, and make a PR when you think you're ready! 

### If you have any questions, do any of the following

- email me - yo@intermine.org
- mention @yochannah
- pop into the intermine support chat - [http://chat.intermine.org](chat.intermine.org)

**Comment by akashp-git** [comment]
Hi yochannah, this is my first time contributing to open source, i would love to fix this.

**Comment by akashp-git** [comment]
Hi @yochannah ,
Let me elaborate on what i understood. Please look into the screenshot.

![screenshot from 2018-02-10 16-08-07](https://user-images.githubusercontent.com/13429505/36061259-0c7e4122-0e7e-11e8-9ee1-cc02efb528c2.png)

Fix
 1) Only the circled points should have title attached and the top four smaller points should be ignored since they are very close to each other.
2) DB identifier should be used as the title.

Let me know if i'm missing anything.

**Comment by akashp-git** [comment]
Might be i overthought the issue.
So these are the modifications required.
1) Add title above the table and also add title above the node info displayed below the table
2) Replace the text 'Double click on a node to load the table.' with 'Double click on a node to load more info about the node and its closest neighbours.'

**Comment by akashp-git** [comment]
HI @yochannah ,

Take a look at the screenshot.
Let me know if these were the changes required so that i can submit a PR.

![modifications](https://user-images.githubusercontent.com/13429505/36072053-ec18eb64-0f3e-11e8-8958-cb1e90bafa12.png)

**Comment by yochannah** [comment]
Hey @a99web - sorry for the slow reply. I probably should put a disclaimer that I generally only check these during weekdays. 

You're right, the second screenshot is more aligned with my thinking and looks good. Please submit the PR and then we can review the code. 

Yo
