### ISSUE TITLE
Change cursor on hover over nodes and edges in d3 graph

### ISSUE THREAD

**Issue by yochannah** [intermine/similarity#11]
## Issue description

In this graph: https://github.com/intermine/similarity/blob/master/Visualisations/top_edges.html, 
when a node is double clicked, a table shows up showing details of the node. Similarly, when it's double clicked, the node and all of its networked nodes shows up. 

It would be nice for the mouse cursor to change to a 'pointer' style cursor (see https://developer.mozilla.org/en-US/docs/Web/CSS/cursor ) when nodes and edges in the graph are hovered over. This helps indicate to a mouse user that it's possible to interact with the nodes and edges, offering better usability. 

## If you'd like to pick this up:

1. Leave a comment to say you're working on the issue
2. Fork the repo, implement the code, and make a PR when you think you're ready! 

### If you have any questions, do any of the following

- email me - yo@intermine.org
- mention @yochannah
- pop into the intermine support chat - [http://chat.intermine.org](chat.intermine.org)

**Comment by nowchris** [comment]
I'd like to tackle this issue!

**Comment by yochannah** [comment]
@nowchris All merged! Thank you so much!
