### ISSUE TITLE
Create D3 (or similar) interactive visualisations for machine learning results data

### ISSUE THREAD

**Issue by yochannah** [intermine/similarity#4]
### Who this task is suitable for: 
 - This is a task with reasonably free reign to create interesting visualisations based on machine learning results. You can learn more about the project in the [final project summary](https://samyadeepblog.wordpress.com/summary/) and read in-depth about algorithms that generated the results in [this blog post](https://samyadeepblog.wordpress.com/2017/07/03/first-blog-post/) 
- ideal for someone who would like to provide an open source contribution but who is comfortable with JS and data visualisation.
- especially good for someone with an interest in machine learning

### What is the task?
Our results data from the similarity project is available here: [https://github.com/intermine/similarity/tree/master/Results](https://github.com/intermine/similarity/tree/master/Results). It would be very nice to put together some interactive visualisations to allow us to explore this data. You can choose what visualisations might be interesting for you to implement. 

### Right, I'm in! How do I get started? 

1. Have a look through the [results folder](https://github.com/intermine/similarity/tree/master/Results) - you may find the blog posts linked above to be useful in understanding the results.
2. Have a think about what visualisations might be interesting and how you'd implement them. Optionally, scribble down a mockup or two of how it might look. 
3. Comment on the task and tell us you want to come play! Share any mocks you may have made. 
4. Get coding! We can advise you on queries relating to InterMine and the similarity project results if you have questions.
5. Once you're ready to make a PR, do so. Remember that small, granular commits are better than big "all in one go" commits and PRs. 

### If you need help

Comment on this issue and mention @joshkh, @yochannah, or check out other ways to contact us, e.g. chat, email: http://intermine.readthedocs.io/en/latest/about/contact-us/

**Comment by rishabh92** [comment]
Hi, Can i work on this one?

**Comment by aswanipranjal** [comment]
Hi @yochannah , @joshkh , I would like to take up this issue.

**Comment by yochannah** [comment]
@rishabh92 @aswanipranjal Hello! Thanks so much for volunteering - I'm looking forward to seeing what you can cook up!

There's probably scope for you both to work on different visualisations - does that sound good? We can use this issue to coordinate - just leave a comment on the issue summing up what you'd like to do, and make sure you don't pick the same option! ;)

**Comment by aswanipranjal** [comment]
Hey, @yochannah! I am currently trying to visualise the `top_edges.txt`  result  file using d3.js and networkx. I am assuming that the tuples of the form `((u'FBgn0004859', u'FBgn0004102'), 0.013733690197390432)`
 in the [file](https://github.com/intermine/similarity/blob/master/Results/top_edges.txtl) represent similar genes, and the 2nd value in the tuple is the magnitude of the connection between the 2 genes.

**Comment by joshkh** [comment]
Hi @aswanipranjal, I think that's a good assumption. Just to make sure let's see if the author of the data @samyadeepbasu agrees.

**Comment by samyadeepbasu** [comment]
Hi,

I agree with the usage of d3 to make the visualisations more interactive!
However as far as I know, d3 doesn't handle large graphs extremely well.
However the datasets on which I run the algorithms are small in nature, so
it might be a good experimentation to see how the visualisations pan out!

--
Samyadeep

**Comment by aswanipranjal** [comment]
Hey, @yochannah, @joshkh. Can you please review the PR and let me know if it works?

**Comment by yochannah** [comment]
All good! You are awesome!
