### ISSUE TITLE
On click, fetch data via webservice and display on page

### ISSUE THREAD

**Issue by yochannah** [intermine/similarity#6]
Thanks to @aswanipranjal we now have a D3 visualisation of our top edges file: https://github.com/intermine/similarity/issues/4 (Demo: [https://yochannah.github.io/similarity/Visualisations/top_edges.html](https://yochannah.github.io/similarity/Visualisations/top_edges.html))

## Background: 

Each node is denoted by identifiers which denote fly genes. For example, the fly gene `FBgn0001325` has a report page on FlyMine: http://www.flymine.org/flymine/portal.do?externalids=FBgn0001325&class=Gene - it is also possible to fetch this data from FlyMine via a webservice. An example minimal data fetch using the im.js library is available here: http://jsbin.com/nuvazuh/edit?html,console

## Task:
Currently, we have a nice tooltip that shows the name of the gene (node) you're hovering over. Expand functionality so that on-click we populate an information box with the following fields, fetched from the web-services:

- [ ] primary identifier
- [ ] secondary identifier
- [ ] organism name
- [ ] gene symbol

- [ ] [optional] Bonus points if this is touchscreen-friendly!

im.js docs: http://alexkalderimis.github.io/imjs/
interactive API docs: http://iodocs.apps.intermine.org/

You may also be interested in #7 

### Right, I'm in! How do I get started?

1. Fork this repo and make sure you can view the visualisation in question. This PR #5 has useful troubleshooting info if needed.  
2. Comment on the task and tell us you want to come play! Share any mocks you may have made.
3. Get coding! We can advise you on queries relating to InterMine and the similarity project results if you have questions.
4. Once you're ready to make a PR, do so. Remember that small, granular commits are better than big "all in one go" commits and PRs.

### If you need help

Comment on this issue and mention @joshkh, @yochannah, or check out other ways to contact us, e.g. chat, email: http://intermine.readthedocs.io/en/latest/about/contact-us/

**Comment by aswanipranjal** [comment]
Hey @yochannah, can I start on this one?

**Comment by yochannah** [comment]
@aswanipranjal Of course! :)

**Comment by aswanipranjal** [comment]
Hey @yochannah, instead of showing all the data in a box like in the tooltip, i've shown it at the bottom and I show the `primaryIdentifier` at the node on  a single click. like this:
![screen shot 2018-01-17 at 11 51 41 pm](https://user-images.githubusercontent.com/9946566/35059730-24899fd6-fbe2-11e7-9346-606a86a42ea3.png)
Will this work?

**Comment by yochannah** [comment]
@aswanipranjal looks great! :+1:

**Comment by aswanipranjal** [comment]
@yochannah, can you please review the pull request?
